import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // MAIN SIDEBAR (everything except auth)
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // root docs
    },
  ],

  // AUTH SIDEBAR (EMPTY so auth pages never appear)
  authSidebar: [],
};

export default sidebars;
