from pydantic import BaseModel, EmailStr
from typing import Optional

class UserProfile(BaseModel):
    id: Optional[str] = None  # UUID will be generated by DB
    email: EmailStr
    username: str
    software_experience: Optional[str] = None
    hardware_robotics_experience: Optional[str] = None
    education_background: Optional[str] = None
    # Add other fields as needed, e.g., reading_progress, preferences
